### ISSUE TITLE
execution expired (Net::OpenTimeout)

### ISSUE THREAD

**Issue by hansode** [hansode/retrobot-verification#14]
```
/home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize': execution expired (Net::OpenTimeout)
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `open'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `call'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:878:in `connect'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /home/vagrant/.rbenv/versions/2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /home/vagrant/retrobot/lib/retrobot/tweet_filters/add_in_reply_to_url.rb:39:in `replace_text'
        from /home/vagrant/retrobot/lib/retrobot/tweet_filters/add_in_reply_to_url.rb:17:in `filter'
        from /home/vagrant/retrobot/lib/retrobot.rb:107:in `block in process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:106:in `each'
        from /home/vagrant/retrobot/lib/retrobot.rb:106:in `process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:82:in `block in tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:76:in `loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:76:in `tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:166:in `main'
        from ./bin/retrobot:12:in `<main>'
```

**Comment by hansode** [comment]
ruby-2.2.0に関しては何度も遭遇・再現する。

**Comment by hansode** [comment]
ruby-2.2.1へupgrade。様子見。

**Comment by hansode** [comment]
解決。
