### ISSUE TITLE
retrobot/lib/retrobot/tweet_filters/tweet.rb:19:in `tweet': undefined method `retryable'

### ISSUE THREAD

**Issue by hansode** [hansode/retrobot-verification#7]
### error message

```
/home/vagrant/retrobot/lib/retrobot/tweet_filters/tweet.rb:19:in `tweet': undefined method `retryable' for #<Retrobot::TweetFilters::Tweet:0x007f84676e4180> (NoMethodError)
        from /home/vagrant/retrobot/lib/retrobot/tweet_filters/tweet.rb:12:in `filter'
        from /home/vagrant/retrobot/lib/retrobot.rb:84:in `block in process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:83:in `each'
        from /home/vagrant/retrobot/lib/retrobot.rb:83:in `process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:72:in `block in tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:70:in `loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:70:in `tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:143:in `main'
        from ./bin/retrobot:12:in `<main>'
```
### result 2015/01/17
- ruby-2.2.0では動かない
- ruby-2.1.5で動く

**Comment by hansode** [comment]
```
$ cat Gemfile.lock
PATH
  remote: .
  specs:
    retrobot (0.3.2)
      activesupport (~> 4.0)
      daemons
      get-twitter-oauth-token
      retryable
      twitter (~> 5.8)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.6)
    buftok (0.2.0)
    daemons (1.1.9)
    diff-lcs (1.2.5)
    equalizer (0.0.9)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    get-twitter-oauth-token (1.1.0)
      oauth
    http (0.6.3)
      http_parser.rb (~> 0.6.0)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.2)
    memoizable (0.4.2)
      thread_safe (~> 0.3, >= 0.3.1)
    minitest (5.5.1)
    multipart-post (2.0.0)
    naught (1.0.0)
    oauth (0.4.7)
    retryable (2.0.0)
    rspec (2.99.0)
      rspec-core (~> 2.99.0)
      rspec-expectations (~> 2.99.0)
      rspec-mocks (~> 2.99.0)
    rspec-core (2.99.0)
    rspec-expectations (2.99.0)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.99.1)
    simple_oauth (0.3.1)
    thread_safe (0.3.4)
    timecop (0.7.1)
    twitter (5.13.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (~> 0.0.9)
      faraday (~> 0.9.0)
      http (~> 0.6.0)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.3.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  retrobot!
  rspec (= 2.99)
  timecop
```

**Comment by hansode** [comment]
https://rubygems.org/gems/retryable

> 2.0.0 - December 3, 2014 (8.5 KB)
> 1.3.6 - September 5, 2014 (9.5 KB)

**Comment by hansode** [comment]
```
$ git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
index db8345d..d5cec0a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,7 +1,7 @@
 PATH
   remote: .
   specs:
-    retrobot (0.3.1)
+    retrobot (0.3.2)
       activesupport (~> 4.0)
       daemons
       get-twitter-oauth-token
@@ -11,33 +11,33 @@ PATH
 GEM
   remote: https://rubygems.org/
   specs:
-    activesupport (4.1.1)
-      i18n (~> 0.6, >= 0.6.9)
+    activesupport (4.2.0)
+      i18n (~> 0.7)
       json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
-      thread_safe (~> 0.1)
+      thread_safe (~> 0.3, >= 0.3.4)
       tzinfo (~> 1.1)
     addressable (2.3.6)
     buftok (0.2.0)
     daemons (1.1.9)
     diff-lcs (1.2.5)
     equalizer (0.0.9)
-    faraday (0.9.0)
+    faraday (0.9.1)
       multipart-post (>= 1.2, < 3)
     get-twitter-oauth-token (1.1.0)
       oauth
-    http (0.6.1)
+    http (0.6.3)
       http_parser.rb (~> 0.6.0)
     http_parser.rb (0.6.0)
-    i18n (0.6.9)
-    json (1.8.1)
+    i18n (0.7.0)
+    json (1.8.2)
     memoizable (0.4.2)
       thread_safe (~> 0.3, >= 0.3.1)
-    minitest (5.3.4)
+    minitest (5.5.1)
     multipart-post (2.0.0)
     naught (1.0.0)
     oauth (0.4.7)
-    retryable (1.3.5)
+    retryable (2.0.0)
     rspec (2.99.0)
       rspec-core (~> 2.99.0)
       rspec-expectations (~> 2.99.0)
@@ -46,10 +46,10 @@ GEM
     rspec-expectations (2.99.0)
       diff-lcs (>= 1.1.3, < 2.0)
     rspec-mocks (2.99.1)
-    simple_oauth (0.2.0)
+    simple_oauth (0.3.1)
     thread_safe (0.3.4)
     timecop (0.7.1)
-    twitter (5.10.0)
+    twitter (5.13.0)
       addressable (~> 2.3)
       buftok (~> 0.2.0)
       equalizer (~> 0.0.9)
@@ -59,8 +59,8 @@ GEM
       json (~> 1.8)
       memoizable (~> 0.4.0)
       naught (~> 1.0)
-      simple_oauth (~> 0.2.0)
-    tzinfo (1.2.1)
+      simple_oauth (~> 0.3.0)
+    tzinfo (1.2.2)
       thread_safe (~> 0.1)

 PLATFORMS
```

**Comment by hansode** [comment]
```
$ git diff retrobot.gemspec
diff --git a/retrobot.gemspec b/retrobot.gemspec
index ff75200..df0c2c6 100644
--- a/retrobot.gemspec
+++ b/retrobot.gemspec
@@ -19,7 +19,7 @@ Gem::Specification.new do |gem|

   gem.add_dependency 'twitter', '~> 5.8'
   gem.add_dependency 'activesupport', '~> 4.0'
-  gem.add_dependency 'retryable'
+  gem.add_dependency 'retryable', '< 2.0'
   gem.add_dependency 'daemons'

   gem.add_development_dependency 'rspec', '= 2.99'
```

**Comment by hansode** [comment]
```
$ rbenv exec bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using addressable 2.3.6
Using buftok 0.2.0
Using daemons 1.1.9
Using diff-lcs 1.2.5
Using equalizer 0.0.9
Using multipart-post 2.0.0
Using faraday 0.9.1
Using oauth 0.4.7
Using get-twitter-oauth-token 1.1.0
Using http_parser.rb 0.6.0
Using http 0.6.3
Using memoizable 0.4.2
Using naught 1.0.0
Installing retryable 1.3.6 (was 2.0.0)
Using simple_oauth 0.3.1
Using twitter 5.13.0
Using retrobot 0.3.2 from source at .
Using rspec-core 2.99.0
Using rspec-expectations 2.99.0
Using rspec-mocks 2.99.1
Using rspec 2.99.0
Using timecop 0.7.1
Using bundler 1.7.12
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by hansode** [comment]
```
$ ./bin/retrobot -c ./retrobot.yml
```

**Comment by hansode** [comment]
```
$ git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
index db8345d..2f0f7e5 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,43 +1,43 @@
 PATH
   remote: .
   specs:
-    retrobot (0.3.1)
+    retrobot (0.3.2)
       activesupport (~> 4.0)
       daemons
       get-twitter-oauth-token
-      retryable
+      retryable (< 2.0)
       twitter (~> 5.8)

 GEM
   remote: https://rubygems.org/
   specs:
-    activesupport (4.1.1)
-      i18n (~> 0.6, >= 0.6.9)
+    activesupport (4.2.0)
+      i18n (~> 0.7)
       json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
-      thread_safe (~> 0.1)
+      thread_safe (~> 0.3, >= 0.3.4)
       tzinfo (~> 1.1)
     addressable (2.3.6)
     buftok (0.2.0)
     daemons (1.1.9)
     diff-lcs (1.2.5)
     equalizer (0.0.9)
-    faraday (0.9.0)
+    faraday (0.9.1)
       multipart-post (>= 1.2, < 3)
     get-twitter-oauth-token (1.1.0)
       oauth
-    http (0.6.1)
+    http (0.6.3)
       http_parser.rb (~> 0.6.0)
     http_parser.rb (0.6.0)
-    i18n (0.6.9)
-    json (1.8.1)
+    i18n (0.7.0)
+    json (1.8.2)
     memoizable (0.4.2)
       thread_safe (~> 0.3, >= 0.3.1)
-    minitest (5.3.4)
+    minitest (5.5.1)
     multipart-post (2.0.0)
     naught (1.0.0)
     oauth (0.4.7)
-    retryable (1.3.5)
+    retryable (1.3.6)
     rspec (2.99.0)
       rspec-core (~> 2.99.0)
       rspec-expectations (~> 2.99.0)
@@ -46,10 +46,10 @@ GEM
     rspec-expectations (2.99.0)
       diff-lcs (>= 1.1.3, < 2.0)
     rspec-mocks (2.99.1)
-    simple_oauth (0.2.0)
+    simple_oauth (0.3.1)
     thread_safe (0.3.4)
     timecop (0.7.1)
-    twitter (5.10.0)
+    twitter (5.13.0)
       addressable (~> 2.3)
       buftok (~> 0.2.0)
       equalizer (~> 0.0.9)
@@ -59,8 +59,8 @@ GEM
       json (~> 1.8)
       memoizable (~> 0.4.0)
       naught (~> 1.0)
-      simple_oauth (~> 0.2.0)
-    tzinfo (1.2.1)
+      simple_oauth (~> 0.3.0)
+    tzinfo (1.2.2)
       thread_safe (~> 0.1)

 PLATFORMS
```

**Comment by hansode** [comment]
`retryable 1.3.6` を使っても同じ結果。

```
/home/vagrant/retrobot/lib/retrobot/tweet_filters/tweet.rb:19:in `tweet': undefined method `retryable' for #<Retrobot::TweetFilters::Tweet:0x007f76555d1fb0> (NoMethodError)
        from /home/vagrant/retrobot/lib/retrobot/tweet_filters/tweet.rb:12:in `filter'
        from /home/vagrant/retrobot/lib/retrobot.rb:84:in `block in process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:83:in `each'
        from /home/vagrant/retrobot/lib/retrobot.rb:83:in `process_line'
        from /home/vagrant/retrobot/lib/retrobot.rb:72:in `block in tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:70:in `loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:70:in `tweet_loop'
        from /home/vagrant/retrobot/lib/retrobot.rb:143:in `main'
        from ./bin/retrobot:12:in `<main>'
```

**Comment by hansode** [comment]
```
$ rbenv exec gem uninstall retryable --version=2.0.0
Successfully uninstalled retryable-2.0.0
```

**Comment by hansode** [comment]
```
$ rbenv exec gem list | grep retry
retryable (1.3.6)
```

**Comment by hansode** [comment]
```
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec bundle exec rspec spec
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
......F..............

Failures:

  1) Retrobot::TweetFilters AddInReplyToUrl#filter adds in_reply_to_url
     Failure/Error: tweet_after = filter.filter tweet_before
     Net::OpenTimeout:
       execution expired
     # ./lib/retrobot/tweet_filters/add_in_reply_to_url.rb:39:in `replace_text'
     # ./lib/retrobot/tweet_filters/add_in_reply_to_url.rb:17:in `filter'
     # ./spec/lib/retrobot/tweet_filters_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 5.17 seconds
21 examples, 1 failure

Failed examples:

rspec ./spec/lib/retrobot/tweet_filters_spec.rb:25 # Retrobot::TweetFilters AddInReplyToUrl#filter adds in_reply_to_url

Randomized with seed 8272

vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

ruby version?

**Comment by hansode** [comment]
2.1.5を試してみる。

```
$ rbenv install 2.1.5
```

**Comment by hansode** [comment]
```
Downloading ruby-2.1.5.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100
Installing ruby-2.1.5...
Installed ruby-2.1.5 to /home/vagrant/.rbenv/versions/2.1.5

```

**Comment by hansode** [comment]
その後の手順も手動で実施。

```
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv version
2.2.0 (set by /home/vagrant/.rbenv/version)
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv global 2.1.5
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv version
2.1.5 (set by /home/vagrant/.rbenv/version)
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
```

**Comment by hansode** [comment]
```
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec gem install bundler
Fetching: bundler-1.7.12.gem (100%)
Successfully installed bundler-1.7.12
Parsing documentation for bundler-1.7.12
Installing ri documentation for bundler-1.7.12
Done installing documentation for bundler after 4 seconds
1 gem installed
```

**Comment by hansode** [comment]
```
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.7.12)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
```

**Comment by hansode** [comment]
```
vagrant@vagrant-centos6:~/retrobot(master)$ git pull
Already up-to-date.
```

**Comment by hansode** [comment]
```
vagrant@vagrant-centos6:~/retrobot(master)$ rbenv exec bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.5.1
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing addressable 2.3.6
Installing buftok 0.2.0
Installing daemons 1.1.9
Installing diff-lcs 1.2.5
Installing equalizer 0.0.9
Installing multipart-post 2.0.0
Installing faraday 0.9.1
Installing oauth 0.4.7
Installing get-twitter-oauth-token 1.1.0
Installing http_parser.rb 0.6.0
Installing http 0.6.3
Installing memoizable 0.4.2
Installing naught 1.0.0
Installing retryable 1.3.6
Installing simple_oauth 0.3.1
Installing twitter 5.13.0
Using retrobot 0.3.2 from source at .
Installing rspec-core 2.99.0
Installing rspec-expectations 2.99.0
Installing rspec-mocks 2.99.1
Installing rspec 2.99.0
Installing timecop 0.7.1
Using bundler 1.7.12
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by hansode** [comment]
```
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
...............F.....

Failures:

  1) Retrobot::TweetFilters AddInReplyToUrl#filter adds in_reply_to_url
     Failure/Error: tweet_after = filter.filter tweet_before
     Net::OpenTimeout:
       execution expired
     # ./lib/retrobot/tweet_filters/add_in_reply_to_url.rb:39:in `replace_text'
     # ./lib/retrobot/tweet_filters/add_in_reply_to_url.rb:17:in `filter'
     # ./spec/lib/retrobot/tweet_filters_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 5.09 seconds
21 examples, 1 failure

Failed examples:

rspec ./spec/lib/retrobot/tweet_filters_spec.rb:25 # Retrobot::TweetFilters AddInReplyToUrl#filter adds in_reply_to_url

Randomized with seed 41497

```

おや・・・？

**Comment by hansode** [comment]
botを起動し、様子見。

**Comment by hansode** [comment]
ruby-2.1.5で動き始めた。

**Comment by hansode** [comment]
### まとめ
- ruby-2.2.0では動かない
- ruby-2.1.5で動く

**Comment by hansode** [comment]
2.2.0 -> 2.1.5

https://github.com/hansode/retrobot-verification/pull/8/files
